name = "omzow"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true

[vars]
PROXYIP = "35.213.132.147"
UUID = "29257b65-550c-481b-8b45-0dd014593934"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
